# Define environment
language: bash
  
# Only build pushes to master branch
branches:
  only:
  - "/^(feature|bugfix)\\/SCC-[0-9]+.*$/"
  - develop
  - main
    
# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:

# SBX - modify CF_ENVIRONMENT as required
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=sbx1 bash ./deploy.sh
  on:
    all_branches: true
    condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/SCC-[0-9]+.*$"

# DEVELOP    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=dev bash ./deploy.sh
  on:
    branch: develop
    
# INT (SIT)    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=int bash ./deploy.sh
  on:
    branch: main
    
env:
  global:
  # ACCESS_KEY_ID 
  - secure: "KXmFuz3PB7sIjOS/wiQ07K8uEHhELu1eCgEorJ1UJMbmJyXodbS32fQJXukuT7NN1KlEL2/0QuWmuKkUC+mopzYBD/ZI37idtwYxIMNOjdU/R+t3GSAzoxdRVdDTVgyq7k58YWthL2ctfODYctX3hj34caSo2snw9r8R1NiNc85WvLEP7UdsusCA+pj41JdOE64iQJnkTRZ3iMLg4aIKJXCE3mB5duNgk7c3Y9UYGQmzCz8bCF9rOMbvBoPvCBHRkz4q+tKGzqrBtM2kdTNQ32qhABo68dxKOCqtQKWiQGIhOY4OSJ6a7wGiqf48r30L1O+qBX5nLy6TGMQog5l7uOj+CQ4KxP86Z5GXBmypOKlE7gojrXFsXPv1Q4yEvPnnHmYf0umS2Xhnbpc5Hy9PidGr6dG3Qo3c4MdyUlhdge/9riuQVOcRuHND3jqbyu9HGLkldX0/GmFKCCRP12V3dj5P1B1LT2/rdI2bMuUp2XB12LsvXu4UyU0QluVLUhu2Uzyh0ChpPgmPq5yp/Pu3h+CyNiOzCapBVlPC3lIAxMC73X9qFvMZMISLf0Hj5sgwdoPVqWNFBRkho1522w5IcfavzsCym7qGJxYz2qyJAcPaQpa0PquYWt7TyMtQtR6+FwPWJCKveItG0pcaOm9APuV2v3ndSQ+3Jsu2ko0OkMQ="
  # SECRET_ACCESS_KEY
  - secure: "Lqs4aSdu3jYY3Vb2GeeeCvGKimLjcGFVOONVbHyQH/rrNpJ7VugBPKc6JG9bo3P0ftGcjqrbe7Q8mbHpsu61plmn17MvhNK1UZTH9OxJoAYYxTL12lVqhSqcHoDOfybw3lTbYVl+L3vuaDtopSKoymr9yrCLaAIqg5gtF+GXuNbrdBNHDiDLRZHOtFXLnOq607tJdoUStCM6yXw5pHvhGd0z1Llj85o71nS/a+5Mt18qs32O21FA0HTwoHpMJ5xwj6LpyTW5LqUf/AXnDL8ssAzKg6QX70yrBTKbxtmDBjOHGF3mFtOq8K00iyTIvz8u8tLF3sUEqpCfFKd7MgrMVjKa4wDRYKGjh3fIWKQn7onkoEPxRC0ssaKhQElo8B284pF9VdPITzHjoXpdoj9T7vmAyU7/2LYDUrGtrKlERb4FjUMHg04QeVSGXqKZY/mEXMTdTJw7mUsHP4DDsG0v0Eo/rIFwksBOGDOOriuklFSRJTz9Jwd2zwqZpn9+B8tFvcCLv81y/ixSuHzsaGQZC2EUQIbyN35n3FtjY79ij1AZMLd89kVl360D/4OkgCzopUfKV9yBoNUeYxQ+9C5BXu2fBUplJjdZtmhBbUzfvpRc/Gh8MZCZto5epFH0PosrtInrhWTjK1IVyy4CPuKrvf0Zds1nqrTj4vWvQALMysU="
  # S3_STATE_BUCKET_NAME
  - secure: "eWgexEHQem45XX+xtLZ6iC23/dKyUADhLQNVn+5z2J1aceZ0KPgSGrzZEKtcfesWO7AxcipsNElC1fzqONuIkQkvq+Juez/mUB72xfH8s1Wxlaioh41S4IvoofnS4vEVUocO9S6b0x96Tr8HDtLKkIyrIgIr6KL6KPUK18uK0ay0ohKuYSzfpfmZWUG7DIJdU+daMeRJ/upG2VVuZ7sOE/9ejrScQPCWjqtVhxV/V+F0gNAosobc2Dn7kocBeR9Xojymt8uI1fpkE8LYz5xzjE4x71Oy8tGbsJk5q1FaNsTphj6xemnjqORe5fbLNdegnjpxuKopH7DRyxnlp9axQi8Z4N69QoyAaJWnU6ut5SSF+SFu0NFvXgiN79MQF/2GlKHb2FltIvFnjr+uaY9G6mjShTSMZNV6pwabuWE11jbkl5Aw5LYbje/Mf+DOLjvSyGuCdP1TeHA8AX3jTNvkewrRiHxJzocqxBJNnlC3vkphF92+x6Bowvkg/eDA5YNo5D6XLXxzs6hf7gMldx//SjE+nXoxzC63DtHm05wsndjcbV+vhLjKoEk1gNWoKveVCc00Jt18L4FURV43XSTU1p2m3FTAcwj68d7DeP4VTca/KRa90bKRL+hFuxaqPrQ/FQW3BgZf3cpxvAi7Ta/hp5HsdmGzMWOqrXUUtjGfHpw="
  # CF_USERNAME
  - secure: "R/tEfsd1wiN1qDrxshcVFYCQENy/PfWjJx24pflk0Zp6PHOaG9x8jGum8EjbisLuZJlgm62FDnHkviWAl0ROF3P4OYmMispY56jvSDNDPea6KTCtAWmXTGlrqjCJ0PHMlZ9JJoeIXFSNX5nlhTJymopfK+HN0Vgdi4Mao2J3pzAAmoLov61WXyHBztSZq9LV+RmL0hNpmYBWEFdnLpOSRCa87O8uFc17hMezV7TPfjUNXnF9LqH5gnuuOQrbE5ubZaBtaa6fBTsnoqG9ntYEoDCn3pc3eWS/ep8UnqSdYhUpsYKqHP/bFZRbtOecUiiOWgH4GBc92TUlmdgR2NG5AzlnIMyaZ2Dv6QQsP1XEuEmdrEbvzP9cbJFPi3a92TfAIs+DKW5c/fPgr++29NhnHFxboyqZiG/T8qCHwdwlivFdtPo+KlTlPN1wGISrzEgu4NbiOXbYyAIhKbFFKqAUr8sBxN00+7cYO3QjHs6tikqB6hMBJTbn4ia5JMRZfdkC4WT7IQCwlnJl7PiiYRbku6CCwCgAqkYyl7Yh8rxtUBD+Ke99sbF5At7CRUcP/Dn+w4dndxwL3rvfUUI4Sgnt4/myTykq+bE/JqEYHz33Bm1SfrfNjKWpD6rr4UmnqWdx/OSh7SGDXNXn2rOh8HFNcAZLmSAuYZx/f/1O8tkVNzc="
  # CF_PASSWORD
  - secure: "i2yjVNX4BNlX5PRnaBkwhmKOfkX2s2eVIHv8ByiCQEy/ARJFyfOArx8RuWGQekeXQ9zHrfA7FH7MS4uEmmeh3JF210Q1yqNhxL+rxzH/6QmRknvpEt9bJ6eXboUVra6BTyCyg2mZtbzKAMaNDeg4W2f9Ke1+X5iIMn1LK9ciZyBk4guZhBe5sDUHRmxJKxNizAjugdS0+CoLNa7K4LYFftVpFKMKCqfeLyVYa6y+wXcCpoCUcmXeyYAnBidFpTZMMy60p8SThxXNDFS4jJJMuruEW4rwTWpfOlmhU5QqVJp4/OpbHkF+sJAuvbzaZ7cMzErfRcsXS0kYXZmhJSXb5bpjuZSNFcFR5bC2yOWlbzfqhhhKymk10e0ghUrFlWXqoQ/9IUo4qFN8GEsJlYKuwHU5kBQtRbqEVHkSuzw91Oje5zNKQ66ZmUjjg9iAMUxIavpsJ6Gy8sSOWY3FmGGDUzi1LRz0M+aKBS7hY0NKsalctlAOLeis/baTh8BtXgNzYsxXLXdG/ogcylv2iIVEkV/EVXB789hPZcLVG2aSis8WBrQSxXBImbqpfiqCdOJvU7KZKAtQm+kl7KSvPNm7bx+J4+bwcMTy9uONh+6SyEXzcijO+z5PDc/gQe1EbYBRVN5AG221izKSYgtRoQRiRl26o1Sdlef/nXZ2PojAjNQ="
  - TF_VERSION=1.0.5
