# Define environment
language: bash
  
# Only build pushes to master branch
branches:
  only:
  - "/^(feature|bugfix)\\/SCC-[0-9]+.*$/"
  - develop
  - main
    
# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:

# SBX - modify CF_ENVIRONMENT as required
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=sbx1 bash ./deploy.sh
  on:
    all_branches: true
    condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/SCC-[0-9]+.*$"

# DEVELOP    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=dev bash ./deploy.sh
  on:
    branch: develop
    
# INT (SIT)    
- provider: script
  skip_cleanup: true
  script: CF_ENVIRONMENT=int bash ./deploy.sh
  on:
    branch: main
    
env:
  global:
  # ACCESS_KEY_ID 
  - secure: "qTYaXfTCqUib4reX8pWp1rC5+JoyFixj+sxowWUOyWKfp2NARXw4eSyat8l+LvANQXUkO9egCuukjSCMqDQdJYaTXMNgksRa2STQoUct+5p2FctbHB/07/EZI7pFhfEqL2CjM5ChtNP7d5kGLEYFo1R3oblQ6Qaz7g0J/PnWjjW/mC44QaBniT6QQim20kjLO/Ip0cf29B7ZXeGYwcCDQe40+Fs3xaMuXpvcfrHVZ8WXYfHSQDLBy6N0mnzEvyQarqZnO60KkgLgp+WaC46hm40pI0N/gZR2Ncd3FAKeMfKsmN17uk2SM2adFwyCeEkKxX6I/9RtwyJKFQZznc9gZ8RaGMY1KOcHwzX25IeWnyj1QcqJlR4Co6l13VLoF665NCkbi5lYcts+8naw3gBuYxeJx/8lM8SnSXPHQZdEgeGZ42rgtcQYyjjzpgMkUN99/uHUDSnsSASwS07Qu0tDwRwamgjwOGVeWUpigrMMkFLebBnjUV0OJccSBdtfznUTrUdFHSztjS1T29nXIx2LScPq61++Qf9k8eDHW5KmhUw7zmTd2U57YRmsnjxUhq11EHWlpty+DB0ekY1ulBrD3ntHAd4H6qMio7FuXkffRXve3Sw6ZcMPSJu0ev05w8YY8u6CwfbTV4s8V6/41Ix9j1N9fLuySIUb1OudtpvAV9g="
  # SECRET_ACCESS_KEY
  - secure: "G06sjnxVCuYZF6NGUJZhOEtLunA17WKQ1dpavpGVCiQMrVQf6e/h2PHM7vaE+8Ms7h0ETPq7fYUGgsOnHUeeRZcSg90DLYFRf9WOq35oHCzSeEAqC+JG2qlqaNyiB/kR2TBipsnqKf6fahVT7INFwaoK/EAd2ZdyB54i2ce8eH+xX0iNAB0HWyUAmzpG/riISA56qH3WVWMwVd3HTqZYkB5onTNgALmHLW74cQU6M7dpmvez7jXIb//InQuNdTag+idWXbQvE6PK/yBPVaqUxbe0RH8j0/GVPxwt15+W/nfDnRoEna8M/YSgmp/30K6QGR3MaSwgWFzW7C6PQ7rMKykRLeVikCxKR/3oURyWoWzQHxsAI7dp9ueU7AXA6c8u6qyyHuR8DTXfYrE3/qEPKi2K6rxSn9z2cICFxLSRrKefwKp8S+wN7DBWTiGyTpzUJhTsfpFU7dtTumcQvaxe0ySrzStI8ihqq2vT68hYeY4Q8JxkF/jQYwqMDQP6zsufnNryVWmDZG7dJKrVO3MDPHVknLNOQ99aY7+VdnAEJhl7RzTYTnKoMH4s3Nl5SCH4F+vraCwJutVLF3ayRWwTH0yXeapU9QVzENRkXjzz2VuS37XXd7YtAruRvmz2tdcajbkBjueCaQbMRNHOQmzBE8l44pVV5QzwR4m143QqKsY="
  # S3_STATE_BUCKET_NAME
  - secure: "rtjTApe3isPSnDNANpoGauq6zNWACm89KrtEpDekvRQOEo/MunVf49z8u4GYO+ioOsVNxBHRgLdWtj7WZYexh3jYvM5kk13DKDxDoEU9CLFeER0x9qfIpWRZIS7d1PjvN050IjqtWsJh1fFFplAT4nu2zR6UtLtM8RKksVHVJ0maEFiWyXwqapTGqwbmlO9MN8WbuqpmVndKHKJ/rOdphIBRFA6Vq8TbkiQV4yTAM4rQ5G8tDl4UI5o1xhpx3+//IVWTWLgOag0//+ZyNvSHlHz87+ZqwJEPkvg+DSnWziKVBlbadeGq8n8nwwSZysLqyHbqtb8yGI0b/yZfSmTVfYhFiknDA2Q3ZkVx3uqgsCNUFq9+hfXi0KDC7Hh3wSLsn+7h7bxHIk2oBz0chjKevYaupLAw3Hb1PmnjaX9W/DaUP0h+9hyIYIcuR++rFYJOzXq05tsIEKnt/up56zUKf3ZKPR3U8UcIoL0FJ+Rfx7fWZooHhl6RSbwTUyIe2PS5dZWI1JGEFOLoreRInfarseBlWWNNRuBwwyppFVoVT+ecZke5/OJnNAqf3bkAERNRuhJYDbLj7mCSTU+24wEghzmJdhSEPECKK3pTL50OweOpzb25KeIkpXU8M8XwZdiTIOex3rWMtX1OvOnwVyvCQLZSxsOnVBXe+cG+aglYgo0="
  # CF_USERNAME
  - secure: "F+MxT/DYsPx5xP2BUG68L9eK2FiWEqVVYMCSWqyAzuX8pazHTo9ZnIWCse97RHUhwScX94dxMWkTSswc50FYSaPQpgUd0yDWPz12qMpa4au2+UEZE6/ICTWxSCxRGiPDw56DAMRwKbVNQGNaMg46j2ltiueTLEEVEHTw6JpWngVfy7fVfdenhePsinhFdqSgMFNg1cm8XT78elN3iHeAqTvSWhj/4DSlNcByIEN8vdWEWW8duQYxAT4n0Krkyr053k554uilDNS0Fuovx1bCZJLr6dF4EEqsN7N7QFlscKzFVLUDDnKLidwBghX8+m3rDudhiHQ0CwSN/IAUQ70x5FC6HiiFPi5AvdOxYJnhx1keBuFPQ/pbblVn0AKqqSt4FZ3ajOdmlgPFEH2OQkDuL6ru+ZFw+f8URSZmKOrrqvtC23l7p0cGFzAJyjlbQf9cWw+ey54CgyzAboYS6Yd+vC0ejtjyPQoEM1S0uu8SYdcDmfu+ONBcJHZBIG1S7JTVk6Q+3WTXQ/BPv3CT+LAE5+ZnLzRu+HjesgeCBmnNl0xEKpU4nMvMf2c0DXFE5xHtM9UgmR2y7V7e9Qi8MixHIHWxaA3iiQBO4bEOmfVZomppS08ZrbBOmlCWMY3nobxaAbhL10+HRg/5wFsJs6bJsVwDS8XDbY/7z8tTAkbA14Q="
  # CF_PASSWORD
  - secure: "LWICDKnyD1933sOQaQAiPjEYB3xmeO+9m9aNX7xmqBUlFkjDJlOwMu377pz0B8L18ycjQR+TdYDURxLkGt3Z85DTb2iTevauXVfeMl7OGPnM7lnaac1I6Ro0rUQXlTpjJuCJY7PNw3YdkjdFdCMIlZarbTz+dzjXVsYmeLOZfBYlnSDVE+cFbmMlEhSF7V0NYt4pZF0lw+3zJliqTi3aEBoRhG4byStsks/pUw5WWR/qybuqtfhKN7T88TeW4pt+SAgtFq7JDlEEU6lTzFdE5dPcBnXSJAWnkgzf+lX6RUjoExmFS8YAE9Y8xvot/Ax9zYbqouQeim8CzyyYa4Cs66E1mCKJjCv0ZWE4cHeX/WI7C6HKr7i9XHxtI+OQcFs+tD1yPfLPB+JyueTXSIDn+87IM+bRqmARwGaBXAZ8trSHwOB1AGlfcAJO1edddzywifoOzDlIJ4xQfjRyLWw9hyoxDbq2jlRsHAy7+J7w5TfG3cuV7LW3S4TwmojCrKWT/FJA4piBBWCBpSgE/3wd8a7V1s8AdRc+ve7ul9x39d9f9wALpbcd3gLHzzwFGl975CM1ttECFNv2AFR80NeqneElNea2+N0BfGrnTBRkecpXd7gb1EFUmYQRpSsVCSkEOrNapO91WJd0yD/IekbqjqbJy40cb8BjurzpXnw6ICM="
  - TF_VERSION=1.0.5
